' ============================================================================
' vMix 29 shortcut/API function reference
' ============================================================================
' Generated from the official vMix 29 help:
' https://www.vmix.com/help29/ShortcutFunctionReference.html
'
' This catalog is reference data. It does not send commands to vMix.
' The sender classes remain responsible only for HTTP or TCP communication.
'
' The official table lists Name, Category, and Parameters. Some functions
' accept optional details such as SelectedName or SelectedIndex; read the
' official help page before using an unfamiliar function.

Public Class VmixFunctionInfo

    Public Sub New(category As String, name As String, parameters As String)
        Me.Category = category
        Me.Name = name
        Me.Parameters = parameters
    End Sub

    Public ReadOnly Property Category As String
    Public ReadOnly Property Name As String
    Public ReadOnly Property Parameters As String

    ' Returns True when the official parameter list contains this parameter.
    Public Function HasParameter(parameterName As String) As Boolean
        If String.IsNullOrWhiteSpace(parameterName) Then Return False

        For Each item As String In Parameters.Split(","c)
            If String.Equals(item.Trim(), parameterName, StringComparison.OrdinalIgnoreCase) Then Return True
        Next

        Return False
    End Function

    Public ReadOnly Property NeedsInput As Boolean
        Get
            Return HasParameter("Input")
        End Get
    End Property

    Public ReadOnly Property NeedsValue As Boolean
        Get
            Return HasParameter("Value")
        End Get
    End Property

    Public ReadOnly Property NeedsMix As Boolean
        Get
            Return HasParameter("Mix")
        End Get
    End Property

    Public ReadOnly Property NeedsDuration As Boolean
        Get
            Return HasParameter("Duration")
        End Get
    End Property

End Class

Public NotInheritable Class VmixFunctionCatalog

    Public Const ReferenceVersion As Integer = 29
    Public Const OfficialReferenceUrl As String = "https://www.vmix.com/help29/ShortcutFunctionReference.html"

    ' The complete function list is created once when this class is first used.
    Public Shared ReadOnly Functions As IReadOnlyList(Of VmixFunctionInfo) = CreateFunctions()

    Private Sub New()
    End Sub

    ' Finds a function without requiring exact upper/lower-case spelling.
    ' Returns Nothing when the name is not present in the vMix 29 reference.
    Public Shared Function FindByName(name As String) As VmixFunctionInfo
        For Each item As VmixFunctionInfo In Functions
            If String.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase) Then Return item
        Next

        Return Nothing
    End Function

    Private Shared Function CreateFunctions() As IReadOnlyList(Of VmixFunctionInfo)
        Return New List(Of VmixFunctionInfo) From {
            New VmixFunctionInfo("General", "ActivatorRefresh", "None"),
            New VmixFunctionInfo("General", "CallManagerShowHide", "None"),
            New VmixFunctionInfo("General", "KeyPress", "Value"),
            New VmixFunctionInfo("General", "SendKeys", "Value"),
            New VmixFunctionInfo("General", "SetDynamicValue1", "Value"),
            New VmixFunctionInfo("General", "SetDynamicValue2", "Value"),
            New VmixFunctionInfo("General", "SetDynamicValue3", "Value"),
            New VmixFunctionInfo("General", "SetDynamicValue4", "Value"),
            New VmixFunctionInfo("General", "Undo", "None"),
            New VmixFunctionInfo("Audio", "Audio", "Input"),
            New VmixFunctionInfo("Audio", "AudioAuto", "Input"),
            New VmixFunctionInfo("Audio", "AudioAutoOff", "Input"),
            New VmixFunctionInfo("Audio", "AudioAutoOn", "Input"),
            New VmixFunctionInfo("Audio", "AudioBus", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioBusOff", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioBusOn", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioChannelMatrixApplyPreset", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioMixerShowHide", "None"),
            New VmixFunctionInfo("Audio", "AudioOff", "Input"),
            New VmixFunctionInfo("Audio", "AudioOn", "Input"),
            New VmixFunctionInfo("Audio", "AudioPluginOff", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioPluginOn", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioPluginOnOff", "Value,Input"),
            New VmixFunctionInfo("Audio", "AudioPluginShow", "Value,Input"),
            New VmixFunctionInfo("Audio", "BusAAudio", "None"),
            New VmixFunctionInfo("Audio", "BusAAudioOff", "None"),
            New VmixFunctionInfo("Audio", "BusAAudioOn", "None"),
            New VmixFunctionInfo("Audio", "BusAAudioPluginOff", "Value"),
            New VmixFunctionInfo("Audio", "BusAAudioPluginOn", "Value"),
            New VmixFunctionInfo("Audio", "BusAAudioPluginOnOff", "Value"),
            New VmixFunctionInfo("Audio", "BusAAudioPluginShow", "Value"),
            New VmixFunctionInfo("Audio", "BusBAudio", "None"),
            New VmixFunctionInfo("Audio", "BusBAudioOff", "None"),
            New VmixFunctionInfo("Audio", "BusBAudioOn", "None"),
            New VmixFunctionInfo("Audio", "BusBAudioPluginOff", "Value"),
            New VmixFunctionInfo("Audio", "BusBAudioPluginOn", "Value"),
            New VmixFunctionInfo("Audio", "BusBAudioPluginOnOff", "Value"),
            New VmixFunctionInfo("Audio", "BusBAudioPluginShow", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudio", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudioOff", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudioOn", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudioPluginOff", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudioPluginOn", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudioPluginOnOff", "Value"),
            New VmixFunctionInfo("Audio", "BusXAudioPluginShow", "Value"),
            New VmixFunctionInfo("Audio", "BusXSendToMaster", "Value"),
            New VmixFunctionInfo("Audio", "BusXSendToMasterOff", "Value"),
            New VmixFunctionInfo("Audio", "BusXSendToMasterOn", "Value"),
            New VmixFunctionInfo("Audio", "BusXSolo", "Value"),
            New VmixFunctionInfo("Audio", "BusXSoloOff", "Value"),
            New VmixFunctionInfo("Audio", "BusXSoloOn", "Value"),
            New VmixFunctionInfo("Audio", "MasterAudio", "None"),
            New VmixFunctionInfo("Audio", "MasterAudioOff", "None"),
            New VmixFunctionInfo("Audio", "MasterAudioOn", "None"),
            New VmixFunctionInfo("Audio", "MasterAudioPluginOff", "Value"),
            New VmixFunctionInfo("Audio", "MasterAudioPluginOn", "Value"),
            New VmixFunctionInfo("Audio", "MasterAudioPluginOnOff", "Value"),
            New VmixFunctionInfo("Audio", "MasterAudioPluginShow", "Value"),
            New VmixFunctionInfo("Audio", "SetBalance", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetBusAVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusAVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetBusBVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusBVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetBusCVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusCVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetBusDVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusDVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetBusEVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusEVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetBusFVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusFVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetBusGVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetBusGVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetGain", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetGainChannel1", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetGainChannel2", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetHeadphonesVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetMasterVolume", "Value"),
            New VmixFunctionInfo("Audio", "SetMasterVolumeFade", "Value"),
            New VmixFunctionInfo("Audio", "SetVolume", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixer", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerA", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerB", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerC", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerD", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerE", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerF", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerG", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeBusMixerM", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannel1", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannel2", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer1", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer10", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer11", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer12", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer13", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer14", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer15", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer16", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer2", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer3", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer4", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer5", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer6", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer7", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer8", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeChannelMixer9", "Value,Input"),
            New VmixFunctionInfo("Audio", "SetVolumeFade", "Value,Input"),
            New VmixFunctionInfo("Audio", "Solo", "Input"),
            New VmixFunctionInfo("Audio", "SoloAllOff", "None"),
            New VmixFunctionInfo("Audio", "SoloOff", "Input"),
            New VmixFunctionInfo("Audio", "SoloOn", "Input"),
            New VmixFunctionInfo("Audio", "SoloPFL", "Input"),
            New VmixFunctionInfo("Audio", "SoloPFLOff", "Input"),
            New VmixFunctionInfo("Audio", "SoloPFLOn", "Input"),
            New VmixFunctionInfo("Transition", "CutDirect", "Input"),
            New VmixFunctionInfo("Transition", "FadeToBlack", "None"),
            New VmixFunctionInfo("Transition", "QuickPlay", "Input"),
            New VmixFunctionInfo("Transition", "SetFader", "Value"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput1", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput2", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput3", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput4", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput5", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput6", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput7", "Input"),
            New VmixFunctionInfo("Transition", "SetStingerGTInput8", "Input"),
            New VmixFunctionInfo("Transition", "SetTransitionDuration1", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionDuration2", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionDuration3", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionDuration4", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionEffect1", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionEffect2", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionEffect3", "Value"),
            New VmixFunctionInfo("Transition", "SetTransitionEffect4", "Value"),
            New VmixFunctionInfo("Transition", "Stinger1", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger2", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger3", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger4", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger5", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger6", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger7", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Stinger8", "Input,Mix"),
            New VmixFunctionInfo("Transition", "Transition1", "None"),
            New VmixFunctionInfo("Transition", "Transition2", "None"),
            New VmixFunctionInfo("Transition", "Transition3", "None"),
            New VmixFunctionInfo("Transition", "Transition4", "None"),
            New VmixFunctionInfo("Output", "Fullscreen", "None"),
            New VmixFunctionInfo("Output", "FullscreenOff", "None"),
            New VmixFunctionInfo("Output", "FullscreenOn", "None"),
            New VmixFunctionInfo("Output", "SetOutput2", "Value,Input,Mix"),
            New VmixFunctionInfo("Output", "SetOutput3", "Value,Input,Mix"),
            New VmixFunctionInfo("Output", "SetOutput4", "Value,Input,Mix"),
            New VmixFunctionInfo("Output", "SetOutputExternal2", "Value,Input,Mix"),
            New VmixFunctionInfo("Output", "SetOutputFullscreen", "Value,Input,Mix"),
            New VmixFunctionInfo("Output", "SetOutputFullscreen2", "Value,Input,Mix"),
            New VmixFunctionInfo("Output", "Snapshot", "Value"),
            New VmixFunctionInfo("Output", "SnapshotInput", "Value,Input"),
            New VmixFunctionInfo("Output", "StartExternal", "None"),
            New VmixFunctionInfo("Output", "StartMultiCorder", "None"),
            New VmixFunctionInfo("Output", "StartRecording", "None"),
            New VmixFunctionInfo("Output", "StartSRTOutput", "Value"),
            New VmixFunctionInfo("Output", "StartStopExternal", "None"),
            New VmixFunctionInfo("Output", "StartStopMultiCorder", "None"),
            New VmixFunctionInfo("Output", "StartStopRecording", "None"),
            New VmixFunctionInfo("Output", "StartStopSRTOutput", "Value"),
            New VmixFunctionInfo("Output", "StartStopStreaming", "Value"),
            New VmixFunctionInfo("Output", "StartStreaming", "Value"),
            New VmixFunctionInfo("Output", "StopExternal", "None"),
            New VmixFunctionInfo("Output", "StopMultiCorder", "None"),
            New VmixFunctionInfo("Output", "StopRecording", "None"),
            New VmixFunctionInfo("Output", "StopSRTOutput", "Value"),
            New VmixFunctionInfo("Output", "StopStreaming", "Value"),
            New VmixFunctionInfo("Output", "StreamingSetKey", "Value"),
            New VmixFunctionInfo("Output", "StreamingSetPassword", "Value"),
            New VmixFunctionInfo("Output", "StreamingSetURL", "Value"),
            New VmixFunctionInfo("Output", "StreamingSetUsername", "Value"),
            New VmixFunctionInfo("Output", "WriteDurationToRecordingLog", "Value"),
            New VmixFunctionInfo("Title", "AdjustCountdown", "Value,Input"),
            New VmixFunctionInfo("Title", "ChangeCountdown", "Value,Input"),
            New VmixFunctionInfo("Title", "NextTitlePreset", "Input"),
            New VmixFunctionInfo("Title", "PauseCountdown", "Input"),
            New VmixFunctionInfo("Title", "PauseRender", "Input"),
            New VmixFunctionInfo("Title", "PreviousTitlePreset", "Input"),
            New VmixFunctionInfo("Title", "ResumeRender", "Input"),
            New VmixFunctionInfo("Title", "SelectTitlePreset", "Value,Input"),
            New VmixFunctionInfo("Title", "SetColor", "Value,Input"),
            New VmixFunctionInfo("Title", "SetCountdown", "Value,Input"),
            New VmixFunctionInfo("Title", "SetImage", "Value,Input"),
            New VmixFunctionInfo("Title", "SetImageVisible", "Input"),
            New VmixFunctionInfo("Title", "SetImageVisibleOff", "Input"),
            New VmixFunctionInfo("Title", "SetImageVisibleOn", "Input"),
            New VmixFunctionInfo("Title", "SetText", "Value,Input"),
            New VmixFunctionInfo("Title", "SetTextColour", "Value,Input"),
            New VmixFunctionInfo("Title", "SetTextVisible", "Input"),
            New VmixFunctionInfo("Title", "SetTextVisibleOff", "Input"),
            New VmixFunctionInfo("Title", "SetTextVisibleOn", "Input"),
            New VmixFunctionInfo("Title", "SetTickerSpeed", "Value,Input"),
            New VmixFunctionInfo("Title", "StartCountdown", "Input"),
            New VmixFunctionInfo("Title", "StopCountdown", "Input"),
            New VmixFunctionInfo("Title", "SuspendCountdown", "Input"),
            New VmixFunctionInfo("Title", "TitleBeginAnimation", "Value,Input"),
            New VmixFunctionInfo("Input", "ActiveInput", "Input,Mix"),
            New VmixFunctionInfo("Input", "AddInput", "Value"),
            New VmixFunctionInfo("Input", "AutoPauseOff", "Input"),
            New VmixFunctionInfo("Input", "AutoPauseOn", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayFirst", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayFirstOff", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayFirstOn", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayNext", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayNextOff", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayNextOn", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayOff", "Input"),
            New VmixFunctionInfo("Input", "AutoPlayOn", "Input"),
            New VmixFunctionInfo("Input", "AutoRestartOff", "Input"),
            New VmixFunctionInfo("Input", "AutoRestartOn", "Input"),
            New VmixFunctionInfo("Input", "ColourCorrectionAuto", "Input"),
            New VmixFunctionInfo("Input", "ColourCorrectionReset", "Input"),
            New VmixFunctionInfo("Input", "CreateVirtualInput", "Input"),
            New VmixFunctionInfo("Input", "DeinterlaceOff", "Input"),
            New VmixFunctionInfo("Input", "DeinterlaceOn", "Input"),
            New VmixFunctionInfo("Input", "Effect1", "Input"),
            New VmixFunctionInfo("Input", "Effect1Off", "Input"),
            New VmixFunctionInfo("Input", "Effect1On", "Input"),
            New VmixFunctionInfo("Input", "Effect2", "Input"),
            New VmixFunctionInfo("Input", "Effect2Off", "Input"),
            New VmixFunctionInfo("Input", "Effect2On", "Input"),
            New VmixFunctionInfo("Input", "Effect3", "Input"),
            New VmixFunctionInfo("Input", "Effect3Off", "Input"),
            New VmixFunctionInfo("Input", "Effect3On", "Input"),
            New VmixFunctionInfo("Input", "Effect4", "Input"),
            New VmixFunctionInfo("Input", "Effect4Off", "Input"),
            New VmixFunctionInfo("Input", "Effect4On", "Input"),
            New VmixFunctionInfo("Input", "GO", "Input"),
            New VmixFunctionInfo("Input", "InputPreviewHide", "Input"),
            New VmixFunctionInfo("Input", "InputPreviewShow", "Input"),
            New VmixFunctionInfo("Input", "InputPreviewShowHide", "Input"),
            New VmixFunctionInfo("Input", "LayerOff", "Value,Input"),
            New VmixFunctionInfo("Input", "LayerOn", "Value,Input"),
            New VmixFunctionInfo("Input", "LayerOnOff", "Value,Input"),
            New VmixFunctionInfo("Input", "ListAdd", "Value,Input"),
            New VmixFunctionInfo("Input", "ListExport", "Value,Input"),
            New VmixFunctionInfo("Input", "ListPlayOut", "Input"),
            New VmixFunctionInfo("Input", "ListRemove", "Value,Input"),
            New VmixFunctionInfo("Input", "ListRemoveAll", "Input"),
            New VmixFunctionInfo("Input", "ListShowHide", "Input"),
            New VmixFunctionInfo("Input", "ListShuffle", "Input"),
            New VmixFunctionInfo("Input", "LivePlayPause", "Input"),
            New VmixFunctionInfo("Input", "Loop", "Input"),
            New VmixFunctionInfo("Input", "LoopOff", "Input"),
            New VmixFunctionInfo("Input", "LoopOn", "Input"),
            New VmixFunctionInfo("Input", "MarkIn", "Input"),
            New VmixFunctionInfo("Input", "MarkOut", "Input"),
            New VmixFunctionInfo("Input", "MarkReset", "Input"),
            New VmixFunctionInfo("Input", "MarkResetIn", "Input"),
            New VmixFunctionInfo("Input", "MarkResetOut", "Input"),
            New VmixFunctionInfo("Input", "MirrorOff", "Input"),
            New VmixFunctionInfo("Input", "MirrorOn", "Input"),
            New VmixFunctionInfo("Input", "MoveInput", "Value,Input"),
            New VmixFunctionInfo("Input", "MoveLayer", "Value,Input"),
            New VmixFunctionInfo("Input", "NextItem", "Input"),
            New VmixFunctionInfo("Input", "NextPicture", "Input"),
            New VmixFunctionInfo("Input", "Pause", "Input"),
            New VmixFunctionInfo("Input", "Play", "Input"),
            New VmixFunctionInfo("Input", "PlayPause", "Input"),
            New VmixFunctionInfo("Input", "PreviewInput", "Input,Mix"),
            New VmixFunctionInfo("Input", "PreviewInputNext", "None"),
            New VmixFunctionInfo("Input", "PreviewInputPrevious", "None"),
            New VmixFunctionInfo("Input", "PreviousItem", "Input"),
            New VmixFunctionInfo("Input", "PreviousPicture", "Input"),
            New VmixFunctionInfo("Input", "RemoveInput", "Input"),
            New VmixFunctionInfo("Input", "ResetInput", "Input"),
            New VmixFunctionInfo("Input", "Restart", "Input"),
            New VmixFunctionInfo("Input", "SaveVideoDelay", "Input,Duration"),
            New VmixFunctionInfo("Input", "SelectCategory", "Value"),
            New VmixFunctionInfo("Input", "SelectIndex", "Value,Input"),
            New VmixFunctionInfo("Input", "SetAlpha", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGainB", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGainG", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGainR", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGainRGB", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGainY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGammaB", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGammaG", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGammaR", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGammaRGB", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCGammaY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCHue", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCLiftB", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCLiftG", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCLiftR", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCLiftRGB", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCLiftY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCCSaturation", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCrop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetCropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetDynamicInput1", "Value"),
            New VmixFunctionInfo("Input", "SetDynamicInput2", "Value"),
            New VmixFunctionInfo("Input", "SetDynamicInput3", "Value"),
            New VmixFunctionInfo("Input", "SetDynamicInput4", "Value"),
            New VmixFunctionInfo("Input", "SetEffect1Strength", "Value,Input"),
            New VmixFunctionInfo("Input", "SetEffect2Strength", "Value,Input"),
            New VmixFunctionInfo("Input", "SetEffect3Strength", "Value,Input"),
            New VmixFunctionInfo("Input", "SetEffect4Strength", "Value,Input"),
            New VmixFunctionInfo("Input", "SetFrameDelay", "Value,Input"),
            New VmixFunctionInfo("Input", "SetInputName", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer10Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer1Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer2Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer3Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer4Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer5Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer6Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer7Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer8Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9Crop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9CropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9CropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9CropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9CropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9Height", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9PanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9PanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9Rectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9Width", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9X", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9Y", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayer9Zoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerAnimated", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicCrop", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicCropX1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicCropX2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicCropY1", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicCropY2", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicHeight", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicPanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicPanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicRectangle", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicWidth", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetLayerDynamicZoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SetPanX", "Value,Input"),
            New VmixFunctionInfo("Input", "SetPanY", "Value,Input"),
            New VmixFunctionInfo("Input", "SetPictureEffect", "Value,Input"),
            New VmixFunctionInfo("Input", "SetPictureEffectDuration", "Value,Input"),
            New VmixFunctionInfo("Input", "SetPictureTransition", "Value,Input"),
            New VmixFunctionInfo("Input", "SetPosition", "Value,Input"),
            New VmixFunctionInfo("Input", "SetRate", "Value,Input"),
            New VmixFunctionInfo("Input", "SetRateSlowMotion", "Value,Input"),
            New VmixFunctionInfo("Input", "SetZoom", "Value,Input"),
            New VmixFunctionInfo("Input", "SharpenOff", "Input"),
            New VmixFunctionInfo("Input", "SharpenOn", "Input"),
            New VmixFunctionInfo("Input", "SwapLayerAnimated", "Value,Input"),
            New VmixFunctionInfo("Input", "VideoCallAudioSource", "Value,Input"),
            New VmixFunctionInfo("Input", "VideoCallConnect", "Value,Input"),
            New VmixFunctionInfo("Input", "VideoCallReconnect", "Input"),
            New VmixFunctionInfo("Input", "VideoCallVideoSource", "Value,Input"),
            New VmixFunctionInfo("Input", "VideoDelayStartRecording", "Input,Duration"),
            New VmixFunctionInfo("Input", "VideoDelayStartStopRecording", "Input,Duration"),
            New VmixFunctionInfo("Input", "VideoDelayStopRecording", "Input,Duration"),
            New VmixFunctionInfo("Input", "WaitForCompletion", "Input,Duration"),
            New VmixFunctionInfo("Input", "ZoomJoinMeeting", "Value,Input"),
            New VmixFunctionInfo("Input", "ZoomMuteSelf", "Input"),
            New VmixFunctionInfo("Input", "ZoomSelectParticipantByName", "Value,Input"),
            New VmixFunctionInfo("Input", "ZoomUnMuteSelf", "Input"),
            New VmixFunctionInfo("Overlay", "MoveMultiViewOverlay", "Value,Input"),
            New VmixFunctionInfo("Overlay", "MultiViewOverlay", "Value,Input"),
            New VmixFunctionInfo("Overlay", "MultiViewOverlayOff", "Value,Input"),
            New VmixFunctionInfo("Overlay", "MultiViewOverlayOn", "Value,Input"),
            New VmixFunctionInfo("Overlay", "OverlayInput1", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput1In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput1Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput1Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput1Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput1Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput2", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput2In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput2Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput2Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput2Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput2Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput3", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput3In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput3Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput3Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput3Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput3Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput4", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput4In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput4Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput4Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput4Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput4Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput5", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput5In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput5Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput5Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput5Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput5Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput6", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput6In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput6Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput6Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput6Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput6Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput7", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput7In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput7Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput7Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput7Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput7Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput8", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput8In", "Input,Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput8Last", "Mix"),
            New VmixFunctionInfo("Overlay", "OverlayInput8Off", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput8Out", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInput8Zoom", "None"),
            New VmixFunctionInfo("Overlay", "OverlayInputAllOff", "None"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput1", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput2", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput3", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput4", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput5", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput6", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput7", "Input"),
            New VmixFunctionInfo("Overlay", "PreviewOverlayInput8", "Input"),
            New VmixFunctionInfo("Overlay", "SetMultiViewOverlay", "Value,Input"),
            New VmixFunctionInfo("PlayList", "NextPlayListEntry", "None"),
            New VmixFunctionInfo("PlayList", "PreviousPlayListEntry", "None"),
            New VmixFunctionInfo("PlayList", "SelectPlayList", "Value"),
            New VmixFunctionInfo("PlayList", "StartPlayList", "None"),
            New VmixFunctionInfo("PlayList", "StopPlayList", "None"),
            New VmixFunctionInfo("Scripting", "ScriptStart", "Value"),
            New VmixFunctionInfo("Scripting", "ScriptStartDynamic", "Value"),
            New VmixFunctionInfo("Scripting", "ScriptStop", "Value"),
            New VmixFunctionInfo("Scripting", "ScriptStopAll", "None"),
            New VmixFunctionInfo("Scripting", "ScriptStopDynamic", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayACamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayAppendLastEventText", "Value"),
            New VmixFunctionInfo("Replay", "ReplayAppendLastEventTextCamera", "Value"),
            New VmixFunctionInfo("Replay", "ReplayAppendSelectedEventText", "Value"),
            New VmixFunctionInfo("Replay", "ReplayAppendSelectedEventTextCamera", "Value"),
            New VmixFunctionInfo("Replay", "ReplayBCamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayBCamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayCamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayCCamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayChangeDirection", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayChangeSpeed", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayCopyLastEvent", "Value"),
            New VmixFunctionInfo("Replay", "ReplayCopySelectedEvent", "Value"),
            New VmixFunctionInfo("Replay", "ReplayDCamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayDCamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayDeleteLastEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayDeleteSelectedEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayDuplicateLastEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayDuplicateSelectedEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayExportLastEvent", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayFastBackward", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayFastForward", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayJumpFrames", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayJumpFramesFastOff", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayJumpFramesFastOn", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayJumpToNow", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayJumpToSelectedInPoint", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayJumpToSelectedOutPoint", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayLastEventCameraOff", "Value"),
            New VmixFunctionInfo("Replay", "ReplayLastEventCameraOn", "Value"),
            New VmixFunctionInfo("Replay", "ReplayLastEventSingleCameraOn", "Value"),
            New VmixFunctionInfo("Replay", "ReplayLive", "None"),
            New VmixFunctionInfo("Replay", "ReplayLiveToggle", "None"),
            New VmixFunctionInfo("Replay", "ReplayMarkCancel", "None"),
            New VmixFunctionInfo("Replay", "ReplayMarkIn", "None"),
            New VmixFunctionInfo("Replay", "ReplayMarkInLive", "None"),
            New VmixFunctionInfo("Replay", "ReplayMarkInOut", "Value"),
            New VmixFunctionInfo("Replay", "ReplayMarkInOutLive", "Value"),
            New VmixFunctionInfo("Replay", "ReplayMarkInOutLiveFuture", "Value"),
            New VmixFunctionInfo("Replay", "ReplayMarkInOutRecorded", "Value"),
            New VmixFunctionInfo("Replay", "ReplayMarkInRecorded", "None"),
            New VmixFunctionInfo("Replay", "ReplayMarkInRecordedNow", "None"),
            New VmixFunctionInfo("Replay", "ReplayMarkOut", "None"),
            New VmixFunctionInfo("Replay", "ReplayMoveLastEvent", "Value"),
            New VmixFunctionInfo("Replay", "ReplayMoveSelectedEvent", "Value"),
            New VmixFunctionInfo("Replay", "ReplayMoveSelectedEventDown", "None"),
            New VmixFunctionInfo("Replay", "ReplayMoveSelectedEventUp", "None"),
            New VmixFunctionInfo("Replay", "ReplayMoveSelectedInPoint", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayMoveSelectedOutPoint", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayPause", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlay", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayAllEvents", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayAllEventsToOutput", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayBackward", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayEvent", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayEventsByID", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayEventsByIDToOutput", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayEventToOutput", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayForward", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayLastEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayLastEventToOutput", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayNext", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayPause", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlayPrevious", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlaySelectedEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayPlaySelectedEventToOutput", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayQuadModeOff", "None"),
            New VmixFunctionInfo("Replay", "ReplayQuadModeOn", "None"),
            New VmixFunctionInfo("Replay", "ReplayRecorded", "None"),
            New VmixFunctionInfo("Replay", "ReplayScrollSelectedEvent", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySelectAllEvents", "None"),
            New VmixFunctionInfo("Replay", "ReplaySelectChannelA", "None"),
            New VmixFunctionInfo("Replay", "ReplaySelectChannelAB", "None"),
            New VmixFunctionInfo("Replay", "ReplaySelectChannelB", "None"),
            New VmixFunctionInfo("Replay", "ReplaySelectedEventCameraOff", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySelectedEventCameraOn", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySelectedEventSingleCameraOn", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents1", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents10", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents11", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents12", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents13", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents14", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents15", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents16", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents17", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents18", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents19", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents2", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents20", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents3", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents4", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents5", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents6", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents7", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents8", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectEvents9", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectFirstEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectLastEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectNextEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySelectPreviousEvent", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySetAudioSource", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySetChannelAToBTimecode", "None"),
            New VmixFunctionInfo("Replay", "ReplaySetChannelAToBTimecodeAndCamera", "None"),
            New VmixFunctionInfo("Replay", "ReplaySetChannelBToATimecode", "None"),
            New VmixFunctionInfo("Replay", "ReplaySetChannelBToATimecodeAndCamera", "None"),
            New VmixFunctionInfo("Replay", "ReplaySetDirectionBackward", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySetDirectionForward", "Channel"),
            New VmixFunctionInfo("Replay", "ReplaySetLastEventText", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySetLastEventTextCamera", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySetSelectedEventText", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySetSelectedEventTextCamera", "Value"),
            New VmixFunctionInfo("Replay", "ReplaySetSpeed", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplaySetTimecode", "Value,Channel"),
            New VmixFunctionInfo("Replay", "ReplayShowHide", "None"),
            New VmixFunctionInfo("Replay", "ReplayStartRecording", "None"),
            New VmixFunctionInfo("Replay", "ReplayStartStopRecording", "None"),
            New VmixFunctionInfo("Replay", "ReplayStopEvents", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayStopRecording", "None"),
            New VmixFunctionInfo("Replay", "ReplaySwapChannels", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleLastEventCamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleQuadMode", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera1", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera2", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera3", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera4", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera5", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera6", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera7", "None"),
            New VmixFunctionInfo("Replay", "ReplayToggleSelectedEventCamera8", "None"),
            New VmixFunctionInfo("Replay", "ReplayUpdateSelectedInPoint", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayUpdateSelectedOutPoint", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayUpdateSelectedSpeed", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayUpdateSelectedSpeedDefault", "Channel"),
            New VmixFunctionInfo("Replay", "ReplayUpdateSelectedSpeedFromValue", "Value,Channel"),
            New VmixFunctionInfo("NDI", "NDICommand", "Value,Input"),
            New VmixFunctionInfo("NDI", "NDISelectSourceByIndex", "Value,Input"),
            New VmixFunctionInfo("NDI", "NDISelectSourceByName", "Value,Input"),
            New VmixFunctionInfo("NDI", "NDIStartRecording", "Input"),
            New VmixFunctionInfo("NDI", "NDIStopRecording", "Input"),
            New VmixFunctionInfo("OMT", "OMTSelectSourceByIndex", "Value,Input"),
            New VmixFunctionInfo("OMT", "OMTSelectSourceByName", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZCreateVirtualInput", "Input"),
            New VmixFunctionInfo("PTZ", "PTZFocusAuto", "Input"),
            New VmixFunctionInfo("PTZ", "PTZFocusFar", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZFocusManual", "Input"),
            New VmixFunctionInfo("PTZ", "PTZFocusNear", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZFocusStop", "Input"),
            New VmixFunctionInfo("PTZ", "PTZHome", "Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveDown", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveDownLeft", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveDownRight", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveLeft", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveRight", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveStop", "Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveToVirtualInputPosition", "Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveToVirtualInputPositionByIndex", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveUp", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveUpLeft", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZMoveUpRight", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZUpdateVirtualInput", "Input"),
            New VmixFunctionInfo("PTZ", "PTZZoomIn", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZZoomOut", "Value,Input"),
            New VmixFunctionInfo("PTZ", "PTZZoomStop", "Input"),
            New VmixFunctionInfo("Preset", "LastPreset", "None"),
            New VmixFunctionInfo("Preset", "OpenPreset", "Value"),
            New VmixFunctionInfo("Preset", "SavePreset", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourceAutoNextOff", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourceAutoNextOn", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourceAutoNextOnOff", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourceNextRow", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourcePause", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourcePlay", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourcePlayPause", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourcePreviousRow", "Value"),
            New VmixFunctionInfo("DataSources", "DataSourceSelectRow", "Value"),
            New VmixFunctionInfo("Browser", "BrowserBack", "Input"),
            New VmixFunctionInfo("Browser", "BrowserForward", "Input"),
            New VmixFunctionInfo("Browser", "BrowserKeyboardDisabled", "Input"),
            New VmixFunctionInfo("Browser", "BrowserKeyboardEnabled", "Input"),
            New VmixFunctionInfo("Browser", "BrowserMouseDisabled", "Input"),
            New VmixFunctionInfo("Browser", "BrowserMouseEnabled", "Input"),
            New VmixFunctionInfo("Browser", "BrowserNavigate", "Value,Input"),
            New VmixFunctionInfo("Browser", "BrowserReload", "Input")
        }
    End Function

End Class
